-- ─────────────────────────────────────────────────────────────────────────
-- Reference schema (Phase 2 of the checklist).
--
-- NOTE: the application creates this table automatically via SQLAlchemy
-- (Base.metadata.create_all on startup), so you do NOT need to run this by
-- hand. It is kept here as documentation and for anyone who prefers to manage
-- the schema with raw SQL / migrations instead of the ORM.
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS jobs (
    job_id       VARCHAR(36) PRIMARY KEY,        -- UUID4 generated by the app
    status       VARCHAR(20)  NOT NULL DEFAULT 'pending',  -- pending|processing|completed|failed
    progress     INTEGER      NOT NULL DEFAULT 0,           -- 0–100 for the UI bar

    source_name  VARCHAR(255),                   -- original filename or 'pasted-text'
    file_path    VARCHAR(512),                   -- path in shared storage
    input_type   VARCHAR(20),                    -- 'file' | 'text'

    result       JSON,                           -- the full AnalysisReport (nested JSON)
    error        TEXT,                           -- failure reason, if any

    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ
);

-- Status is the hot filter for dashboards / queue draining.
CREATE INDEX IF NOT EXISTS ix_jobs_status ON jobs (status);
